name: noobzz CI/CD/DEV

on: 
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message,'[build]')"
    steps:
    - uses: actions/checkout@master
      with:
        ref: master 
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build Java jar
      run: | 
        mvn clean install
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Move files and compress
      run: |
        mkdir -p noobzz_jars
        mv ./noobzz-gateway/target/noobzz-gateway.jar ./noobzz_jars
        mv ./noobzz-auth/target/noobzz-auth.jar ./noobzz_jars
        mv ./noobzz-visual/noobzz-monitor/target/noobzz-visual-monitor.jar  ./noobzz_jars
        mv ./noobzz-modules/noobzz-system/target/noobzz-modules-system.jar ./noobzz_jars
        tar -zcvf  noobzz_jars.tar.gz noobzz_jars/
    - name: Scp file to tencent
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DOCKER_IP }}
        username: ${{ secrets.DOCKER_ID }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        port: ${{ secrets.DOCKER_PORT }}
        source: "noobzz_jars.tar.gz"
        target: "/www/wwwroot/noobzz"
    - name: Distribution and backup
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DOCKER_IP }}
        username: ${{ secrets.DOCKER_ID }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        port: ${{ secrets.DOCKER_PORT }}
        script: |
          cd /www/wwwroot/noobzz
          tar -zxvf /www/wwwroot/noobzz/noobzz_jars.tar.gz
